name: devops test 
on: 
  push: 
    branches: [ main ]
jobs: 
  deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps: 
    - name: get code from github
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo rm -rf devops1
          git clone https://github.com/thanks9807/devops1
          sudo mv -f ./devops1/*.html /var/www/html

    - uses: actions/checkout@v3

      with:
        ref: master

    - name: Playbook 다운로드
      uses: dawidd6/action-download-artifact@v2

      with:
        name: playbook.yml
        path: ./
          
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
    # Optional, directory where playbooks live
        directory: ./
        key: ${{ secrets.KEY }}
        inventory: |
          [all]
          ${{ secrets.REMOTE_HOST }} ansible_ssh_user=ubuntu
          
    
  
  
