name: devops test 
on: 
  push: 
    branches: [main]
jobs: 
  deploy: 
    name: Deploy to EC2
    runs-on: ubuntu-lastest
    
    steps: 
    - name: get code from github
      uses: appleboy/ssh-action@1.0.3
      with:
        host: 43.202.50.215
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          echo test > /tmp/abcd
        
        
        
